### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by Quentins404** [Derpitron/weather-webhook-python#2]
I followed all the steps to make the script works and i get this error on discord : 

```
Script failed on PC_QUENTIN at EUROPE/PARIS00:53:14
[00:53]
Traceback (most recent call last):
  File "c:\Users\canai\Desktop\weather_bot\webhook.py", line 23, in main
    data = get(os.getenv("API")).json()
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\canai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\canai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\canai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'a6a22dc49de7ed4538ed51b95a8a3317': No scheme supplied. Perhaps you meant https://a6a22dc49de7ed4538ed51b95a8a3317?

```

**Comment by Derpitron** [comment]
Hello! This is quite a 2 year old script I made and haven't updated since. It uses the old versions of the Discord and Open Weather Map APIs, so is probably incompatible.
